/**
 * Do not edit directly — generated by Style Dictionary from tokens/tokens.json
 * Run `npm run build:tokens` to regenerate, or push to main (CI runs it automatically)
 */

export const DsColorBrandPrimary = "#0F6FFF";
export const DsColorBrandPrimaryHover = "#0A5AD4";
export const DsColorBrandSecondary = "#10B981";
export const DsColorBrandSecondaryHover = "#059669";
export const DsColorNeutral50 = "#F9FAFB";
export const DsColorNeutral100 = "#F3F4F6";
export const DsColorNeutral200 = "#E5E7EB";
export const DsColorNeutral300 = "#D1D5DB";
export const DsColorNeutral400 = "#9CA3AF";
export const DsColorNeutral500 = "#6B7280";
export const DsColorNeutral600 = "#4B5563";
export const DsColorNeutral700 = "#374151";
export const DsColorNeutral800 = "#1F2937";
export const DsColorNeutral900 = "#111827";
export const DsColorStatusSuccess = "#10B981";
export const DsColorStatusWarning = "#F59E0B";
export const DsColorStatusError = "#EF4444";
export const DsColorStatusInfo = "#3B82F6";
export const DsSpaceNone = "0px";
export const DsSpaceXs = "4px";
export const DsSpaceSm = "8px";
export const DsSpaceMd = "16px";
export const DsSpaceLg = "24px";
export const DsSpaceXl = "32px";
export const DsSpace2xl = "48px";
export const DsSpace3xl = "64px";
export const DsFontFamilySans = "Inter, ui-sans-serif, system-ui, sans-serif";
export const DsFontFamilyMono = "'JetBrains Mono', ui-monospace, monospace";
export const DsFontSizeXs = "0.75rem";
export const DsFontSizeSm = "0.875rem";
export const DsFontSizeBase = "1rem";
export const DsFontSizeLg = "1.125rem";
export const DsFontSizeXl = "1.25rem";
export const DsFontSize2xl = "1.5rem";
export const DsFontSize3xl = "1.875rem";
export const DsFontWeightNormal = "400";
export const DsFontWeightMedium = "500";
export const DsFontWeightSemibold = "600";
export const DsFontWeightBold = "700";
export const DsFontLineHeightTight = "1.25";
export const DsFontLineHeightSnug = "1.375";
export const DsFontLineHeightNormal = "1.5";
export const DsFontLineHeightRelaxed = "1.625";
export const DsRadiusNone = "0px";
export const DsRadiusSm = "2px";
export const DsRadiusMd = "6px";
export const DsRadiusLg = "8px";
export const DsRadiusXl = "12px";
export const DsRadiusFull = "9999px";
export const DsShadowSm = "0 1px 2px 0 rgb(0 0 0 / 0.05)";
export const DsShadowMd = "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)";
export const DsShadowLg = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";
